stratumn/generators

- agent-basic-js/files/agent/index.js
- agent-basic-js/files/agent/package.json
> agent-basic-js: update agent-js

- agent-basic-js/files/README.md
- agent-basic-js/files/agent/package.json
- agent-basic-js/files/agent/test/actions.js
It should be replaced by processify.
> basic-agent-js: remove stratumn mock agent

- .gitignore
- agent-basic-js/files/agent/index.js
- agent-basic-js/files/agent/lib/actions/actions-PROCESS.js
- agent-basic-js/files/agent/test/actions-PROCESS.js
This is a first step to allow injecting new processes into a running agent
> basic-agent-js: load processes from lib/actions

- agent-basic-js/files/config/dev.secret.env
- agent-basic-js/files/config/test.secret.env
> agent-basic-js: fix WIF decoding

- agent-basic-js/files/agent/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/29)
> agent-basic-js: add agentVersion plugin to list of default plugins

- agent-basic-js/files/agent/package.json
- agent-basic-js/files/docker-compose.dev.yml
- agent-basic-js/files/docker-compose.test.yml
- agent-basic-js/files/docker-compose.yml
- agent-basic-js/files/stratumn.json
- agent-basic-js/generator.json
- stratumn-conf/generator.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/32)
> Release sdk 0.2.0

- agent-basic-js/files/agent/package.json
- agent-basic-js/files/docker-compose.yml
Fix docker-compose file
Fix tmpop app name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/35)
> Release sdk 0.2.0-rc1

- agent-basic-js/files/docker-compose.yml
- agent-basic-js/files/fabric/docker-compose.yml
- agent-basic-js/files/fabric/scripts/install.sh
- agent-basic-js/files/stratumn.json
- agent-basic-js/generator.json
Updated the fabricstore config to be compatible with latest store:
- updated the chaincode/network installer in docker-compose using variable .fabricinstaller
- updated the install script so that it checks for network before installing the network (allows to Ctrl+C and restart network without losing data)
- updated the stratumn.json so that fabric network is properly cleaned after running strat down
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/37)
> fabricstore: update config

- agent-basic-js/files/README.md
I added that when I encountered the yarn issue because of babel, but Adrien fixed it so this isn't needed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/39)
> Remove unneeded yarn command

- agent-basic-js/files/config/dev.secret.env
This is now obsolete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/41)
> agent-basic-js: remove obsolete salt

- agent-basic-js/files/stratumn.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/43)
> agent-basic-js: clean properly couchdb

- agent-basic-js/files/docker-compose.yml
- agent-basic-js/generator.json
- cluster/generator.json
- stratumn-conf/generator.json
This update has to be synced with stratumn/go-indigocore#276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/48)
> Define string selection list as map

- agent-basic-js/files/validation/rules.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/52)
> agent-basic-js: update rules format

- agent-basic-js/files/arch/linux/fix-grafana-files-ownership.sh
- agent-basic-js/files/arch/linux/fix-monitoring-files-ownership.sh
- agent-basic-js/files/docker-compose.dev.yml
- agent-basic-js/files/docker-compose.test.yml
- agent-basic-js/files/docker-compose.yml
- agent-basic-js/generator.json
- cluster/files/arch/linux/fix-grafana-files-ownership.sh
- cluster/files/arch/linux/fix-monitoring-files-ownership.sh
- cluster/files/docker-compose.dev.yml
- cluster/files/docker-compose.yml
- cluster/generator.json
We now allow the user to choose if she wants monitoring or not.
The templates are becoming a bit complex, but unfortunately I don't think there's a magic solution: if we want flexibility for our users, we need a lot of templated ifs...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/55)
> monitoring: make it optional

- agent-basic-js/files/docker-compose.yml
- agent-basic-js/files/monitoring/prometheus/prometheus.yml
- cluster/files/docker-compose.yml
- cluster/files/monitoring/prometheus/prometheus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/56)
> monitoring: add fossilizer monitoring

- agent-basic-js/files/agent/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/57)
> agent-basic-js: remove plugin actionArgs

- agent-basic-js/files/README.md
- agent-basic-js/files/docker-compose.dev.yml
- agent-basic-js/files/docker-compose.test.yml
- agent-basic-js/files/docker-compose.yml
- agent-basic-js/generator.json
- cluster/files/README
- cluster/files/docker-compose.dev.yml
- cluster/files/docker-compose.yml
- cluster/generator.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/58)
> Add elasticsearchstore option

- agent-basic-js/files/stratumn.json
- cluster/files/scripts/tm-init.sh
- cluster/files/scripts/tm-linux-post-init.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/60)
> agent-basic-js, cluster: bump tendermint image to 0.17.1

- agent-basic-js/files/README.md
- agent-basic-js/files/agent/index.js
- agent-basic-js/files/agent/package.json
- agent-basic-js/files/agent/test/actions-PROCESS.js
- agent-basic-js/files/docker-compose.dev.yml
- agent-basic-js/files/docker-compose.test.yml
- agent-basic-js/files/docker-compose.yml
- agent-basic-js/files/stratumn.json
- agent-basic-js/generator.json
- cluster/files/README
- cluster/files/docker-compose.dev.yml
- cluster/files/docker-compose.yml
- cluster/files/scripts/tm-init.sh
- cluster/files/scripts/tm-linux-post-init.sh
- cluster/generator.json
- stratumn-conf/generator.json
I will release a rc2, I need to release the changes I pushed to the rc1 branch.
I will push my new updates to master in the future...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/61)
> v0.3.0-rc1

- agent-basic-js/files/README.md
- cluster/files/README
- cluster/files/README.md
Detail monitoring setup and urls.
Fix mardownlint warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/63)
> monitoring: mention in README

- agent-basic-js/files/stratumn.json
- cluster/files/dial/Dockerfile
- cluster/files/dial/dial.sh
- cluster/files/scripts/tm-init.sh
- cluster/files/scripts/tm-linux-post-init.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/65)
> Tendermint 0.18.0

- cluster/files/docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/generators/70)
> cluster: fix elastictmpop cluster
